### ISSUE TITLE
Lookup example?

### ISSUE THREAD

**Issue by timotahti** [NonFactors/MVC6.Lookup#1]
Hi! Do you have an example on using the Lookup (outside MvcTemplate, that is) ?

**Comment by Muchiachio** [comment]
It's almost the same as [MVC 5's Datalist](http://mvc-datalist.azurewebsites.net/), just renamed to lookup. I have an experimental documentation page going, which would be similar to [grid one](http://mvc6-grid.azurewebsites.net/), but it doesn't seem to work as I expected, because there is not much to show. :smile:

**Comment by timotahti** [comment]
Ok, thanks, I'll take a look. You're doing great work! Feel free to close the issue/question.
