### ISSUE TITLE
RTM NuGet package?

### ISSUE THREAD

**Issue by timotahti** [NonFactors/MVC6.Lookup#2]
Hi,

it seems that you have the RTM code already in GitHub but the package is not available via NuGet yet - could you publish it? Thanks!

Regards,
-Timo

**Comment by Muchiachio** [comment]
Yes, I migrated to RTM, because I could no longer compile RC2.
I can't push just yet, because I have a few breaking changes on my local branch to merge before v1.0.
I could publish some kind of 0.9.7 pre-release, if you really need to or I will publish it anyway on sunday if I can't make all of my changes.

**Comment by timotahti** [comment]
OK, no rush. "When it's done" (or Sunday) sounds good. :)
